spodbtify:
  outputs:
    dev:
      type: duckdb
      path: 'dev.spodbtify.duckdb'
      #schema: 'dev'
      threads: 4

    prod:
      type: duckdb
      path: 'prod.spodbtify.duckdb'
      #schema: 'prod'
      threads: 24
  
    test:
      type: duckdb
      path: 'test.spodbtify.duckdb' 
      #schema: spodbtify
      threads: 4

  target: test